# This file was auto-generated by Fern from our API Definition.

from seed.client import AsyncSeedExamples, SeedExamples

from ...utilities import validate_response


async def test_get_exception(client: SeedExamples, async_client: AsyncSeedExamples) -> None:
    expected_response = {
        "type": "generic",
        "exceptionType": "Unavailable",
        "exceptionMessage": "This component is unavailable!",
        "exceptionStacktrace": "<logs>",
    }
    response = client.file.notification.service.get_exception(notification_id="notification-hsy129x")
    validate_response(response, expected_response)

    async_response = await async_client.file.notification.service.get_exception(notification_id="notification-hsy129x")
    validate_response(async_response, expected_response)
